name: test deploy

on:
  push:
    branches:
    - dev
    - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2
      
      - name: Build dist
        run: |
          npm install
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:alpha

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    needs: [build]
    runs-on: [self-hosted, scpc-test]
    steps:
      - name: Deploy
        run: |
          sudo docker rm -f scpc-web
          sudo docker image rm ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:alpha
          sudo docker pull ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:alpha
          sudo docker run --name scpc-web -p ${{secrets.SCPC_PORT}}:80 --restart=always -d ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:alpha
