name: CI/CD

on:
  push:
    branches:
    - main
    - temp
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2
      
      - name: Build dist
        run: |
          npm install
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          sudo docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          sudo docker rm -f scpc-web
          sudo docker image rm ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:latest
          sudo docker pull ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:latest
          sudo docker run --name scpc-web -p ${{secrets.SCPC_PORT}}:80 -d ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:latest
  # deploy:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.DEPLOY_HOST }}
  #         username: ${{ secrets.DEPLOY_USERNAME }}
  #         key: ${{ secrets.DEPLOY_KEY }}
  #         port: ${{ secrets.DEPLOY_PORT }}
  #         script: |
  #           sudo docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #           sudo docker rm -f scpc-web
  #           sudo docker image rm ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:latest
  #           sudo docker pull ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:latest
  #           sudo docker run --name scpc-web -p ${{secrets.SCPC_PORT}}:80 -d ${{secrets.DOCKER_HUB_USERNAME}}/scpc-web:latest
